[package]
name = "bullfinch"
version = "0.1.0"
authors = ["Igor M"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
url = "2.1.0"
scraper = "0.10.1"
crossbeam-channel = "0.3.9"
reqwest = "0.9.2"